/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/budie.gltf')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      Marche: mixer.clipAction(animations[0], group.current),
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Body} />
      <primitive object={nodes.HancheL} />
      <primitive object={nodes.HancheR} />
      <skinnedMesh material={materials.beige} geometry={nodes.BudieMesh.geometry} skeleton={nodes.BudieMesh.skeleton} />
      <mesh material={materials.rouge} geometry={nodes.navMesh.geometry} position={[-11.57, 0.1, -5.26]} />
    </group>
  )
}
